language: php

php:
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer install

script:
  - ./bin/phpunit -c phpunit.xml.dist

addons:
  code_climate:
    repo_token: c7c2310e6e0119559a5b814159b4ed6e8a4e3f4447db84dcef508fef3f60d1d9

after_script:
  - CODECLIMATE_REPO_TOKEN=c7c2310e6e0119559a5b814159b4ed6e8a4e3f4447db84dcef508fef3f60d1d9
  - ./bin/test-reporter
